BUTTON_RESPONSES = [
    "Nothing happened. But maybe something will happen next time? (It won't.)",
    "Wow, absolutely nothing happened. Try again for the same thrilling result.",
    "That click accomplished precisely nothing. Care to experience nothing again?",
    "Click detected. Result: nothing. But surely the next click will be different...",
    "Congratulations! Nothing happened, exactly as promised.",
    "All that effort for... nothing. But don't let that stop you from trying again.",
    "Nothing happened. I repeat: nothing. What were you expecting?",
    "You clicked and the universe remained completely unchanged. One more for good measure?",
    "Breaking news: Button clicked, nothing happened. Film at 11.",
    "That was anticlimactic, wasn't it? Nothing happened. The next click will be equally disappointing.",
    "Nothing happened, but I admire your optimism in thinking something might.",
    "The absence of something happening is still technically something, right? Click again for more nothing.",
    "I could tell you something happened, but we'd both know that's a lie. Try again?",
    "Nothing happened. Your productivity thanks you for this meaningful diversion.",
    "Nothing. Nada. Zilch. Zero. But don't let that discourage you from clicking again.",
    "Your click has been acknowledged and promptly ignored. Feel free to be ignored again.",
    "This button proudly delivers nothing, as advertised. Click again to confirm.",
    "Nothing happened. You knew nothing would happen. Yet here we are.",
    "I've carefully processed your click and determined that nothing should happen. Let's do it again!",
    "The results are in: absolutely nothing happened. Shocking, I know. One more time?",
]
